services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ServerStatsBundle\Controller\:
    resource: '../../Controller/'
  ServerStatsBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  ServerStatsBundle\Repository\:
    resource: '../../Repository/'
  ServerStatsBundle\Service\:
    resource: '../../Service/'
